- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: true
      changed_when: False
    - name: Install ansible.posix for RHEL distros as ansible-core does not ship with ansible.posix
      local_action: command ansible-galaxy collection install ansible.posix
      args:
        creates: /root/.ansible/collections/ansible_collections/ansible/posix
      when:
        - ansible_distribution in ["AlmaLinux"]

  tasks:
   - include: tasks/repositories.yml
   - include: tasks/packages.yml
   - include: tasks/services.yml
   - include: tasks/users.yml
   - include: tasks/ssh-keys.yml
   - include: tasks/security-defaults.yml
   - include: tasks/cron.yml
   - include: tasks/bashconfig.yml
   - include: tasks/scripts.yml
   #- include: tasks/remotemanagment.yml
  handlers:
   - include: handlers/handlers.yml