- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      package:
        update_cache: false
      changed_when: False
    - name: Install ansible.posix for RHEL distros as ansible-core does not ship with ansible.posix
      local_action: command ansible-galaxy collection install ansible.posix
      args:
        creates: /root/.ansible/collections/ansible_collections/ansible/posix
      when:
        - ansible_distribution in ["AlmaLinux"]
  
  tasks:
    - name: Run all tasks
      import_tasks:
        file: tasks/repositories.yml
        #file: tasks/packages.yml
        #file: tasks/services.yml
        #file: tasks/users.yml
        #file: tasks/ssh-keys.yml
        #file: tasks/security-defaults.yml
        #file: tasks/cron.yml
        #file: tasks/bashconfig.yml
        #file: tasks/scripts.yml
        #file: tasks/remotemanagment.yml
  handlers:
   - include: handlers/handlers.yml