- name: Set registry pull through cache if local
  copy:
    src: files/docker-daemon-config.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 644
  when:
    - ansible_distribution in ["Debian", "Ubuntu"]
    - gateway in ["10.50.0.1", "192.168.0.1"]
  notify: Reload Docker