- name: Print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- name: Set registry pull through cache if local
  copy:
    src: files/docker-daemon-config.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 644
  when:
    - ansible_distribution in ["Debian", "Ubuntu"]
    - default_ipv4.network in ['10.50.0.0']
  notify: Reload Docker