- name: Set registry pull through cache if local
  blockinfile:
    path: /etc/docker/daemon.json
    create: true
    marker: "\"// {mark} ANSIBLE MANAGED BLOCK\":"
    block: |
      {
        "registry-mirrors": ["https://images.grish.io"]
      }
  notify: Reload Docker