- name: SSH Service (Debian and Ubuntu versions < 22.10)
  systemd:
    name: sshd
    enabled: true
    state: started
  when:
    - (ansible_distribution == "Debian") or ((ansible_distribution == "Ubuntu") and (ansible_distribution_major_version < "22.10"))

- name: Disable netdata
  systemd:
    name: netdata
    enabled: no
    state: stopped
  ignore_errors: yes #may not be installed on every distro as per standard installs