- name: SSH Service
  systemd:
    name: sshd
    enabled: true
    state: started

- name: Disable netdata
  systemd:
    name: netdata
    enabled: no
    state: stopped
  ignore_errors: yes #may not be installed on every distro as per standard installs