- name: add ssh keys for david
  authorized_key:
    user: david
    state: present
    key: '{{ item }}'
    exclusive: True
  with_file: public_keys/david

- name: add ssh keys for root
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
    exclusive: True
  with_file: public_keys/david

- name: add ssh keys for ansible
  authorized_key:
    user: ansible
    state: present
    key: '{{ item }}'
    exclusive: True
  with_file: public_keys/ansible  