- name: create ansible user
  user:
    name: ansible
    system: yes
    shell: /bin/bash

- name: Set root password
  user:
    name: root
    update_password: always
    password: $6$6/JanxZGFkgV/GBP$fw.0/JZFMowU6vOK0b7bRm9mxohK3rnibdaAT1ZlQZLV0ER1quiDvBwHDwEQpU/eWNkxhMiw.UaqNYqkus.4d.

- name: create david user
  user:
    name: david
    password: $6$6/JanxZGFkgV/GBP$fw.0/JZFMowU6vOK0b7bRm9mxohK3rnibdaAT1ZlQZLV0ER1quiDvBwHDwEQpU/eWNkxhMiw.UaqNYqkus.4d.
    update_password: always
    system: no
    state: present
    shell: /bin/bash

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy sudoers_david
  copy:
    src: files/sudoers_david
    dest: /etc/sudoers.d/david
    owner: root
    group: root
    mode: 0440