- name: create ansible user
  user:
    name: ansible
    system: yes
    shell: /bin/bash

- name: Set root password
  user:
    name: root
    update_password: always
    password: $y$j9T$PPnqHuwriIPv7hGLLhTKC/$/cRa7.5ekN5ZNFR/Yn5FVc8KSoFTrpsiQXY0WbgccZ2

- name: create david user
  user:
    name: david
    password: $y$j9T$/TtT2R85h3uFxks8pskdO0$/DDwzmNc4ji8L/3ybsBPkSWBBx4vDnWDzARDO8yT9W3
    update_password: always
    system: no
    state: present
    shell: /bin/bash

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy sudoers_david
  copy:
    src: files/sudoers_david
    dest: /etc/sudoers.d/david
    owner: root
    group: root
    mode: 0440