- name: create ansible user
  user:
    name: ansible
    system: yes

- name: create david user
  user:
    name: david
    password: $6$VDa6YjExkJMaTB9E$ztcDUTNW.T1l/LlpMYnDfWO2jjS5HBNKgLXB8ovH8mC3Y.rhu8Px7KXKBG7Kb7vzvXyH4CDkSleTVQ9W3m.1h.
    system: no
    state: present
    shell: /bin/bash

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy sudoers_david
  copy:
    src: files/sudoers_david
    dest: /etc/sudoers.d/david
    owner: root
    group: root
    mode: 0440