- name: create ansible user
  user:
    name: ansible
    system: yes

- name: Set root password
  user:
    name: root
    update_password: always
    password: $6$hoR32ATpi9pfw4se$mosQzv.etYw7ruh3QYiAJ7f87nmb4oKBdtP31mPZECOzPCsZRoIMaV5aBFcS9dXf5JGsDUm431XPLOdAJ8Xua.

- name: create david user
  user:
    name: david
    password: $6$hoR32ATpi9pfw4se$mosQzv.etYw7ruh3QYiAJ7f87nmb4oKBdtP31mPZECOzPCsZRoIMaV5aBFcS9dXf5JGsDUm431XPLOdAJ8Xua.
    update_password: always
    system: no
    state: present
    shell: /bin/bash

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

- name: copy sudoers_david
  copy:
    src: files/sudoers_david
    dest: /etc/sudoers.d/david
    owner: root
    group: root
    mode: 0440